language: node_js
node_js:
  - 14.17.1
services:
  - mongodb
deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key: $SECRETACCESSKEY
  region: "ap-southeast-1"
  app: "jonathan-otot-b2.2"
  env: "Jonathanototb22-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-509469594312"
  on:
    branch: master
